### ISSUE TITLE
Compile defs not working for relators

### ISSUE THREAD

**Issue by sweco-semhul** [libris/definitions#1]
On develop branch:
python scripts/compile_defs.py -c cache/ -o build/ relators

results in:
Traceback (most recent call last):
  File "scripts/compile_defs.py", line 414, in <module>
    run(args, opts.outdir, opts.cache)
  File "scripts/compile_defs.py", line 361, in run
    data = datasets[name]()
  File "scripts/compile_defs.py", line 72, in relators
    }, index=('byNotation', 'notation'))
  File "scripts/compile_defs.py", line 207, in to_jsonld
    nodes = data.pop(graph_key)
KeyError: 'byNotation'

**Comment by niklasl** [comment]
Unable to reproduce. Was this run within a virtualenv installed with items from requirements.txt?

**Comment by sweco-semhul** [comment]
yes, weird when I run it I still get the same error. 

![screen shot 2015-02-16 at 13 42 50](https://cloud.githubusercontent.com/assets/2656349/6212125/e79f2d8c-b5e1-11e4-90d2-b9b6f25cb52f.png)

**Comment by niklasl** [comment]
Try --upgrade on rdflib-jsonld to see if there is some change there I've overlooked.

**Comment by niklasl** [comment]
This is no longer a problem.
