### ISSUE TITLE
sab.ttl: Klassifikationens namn delas upp vid komma och ena halvan hamnar i en comment istället för prefLabel

### ISSUE THREAD

**Issue by fontanka16** [libris/definitions#469]
https://github.com/libris/definitions/blob/2cdfbb6620ae9742306d28d51c9de4309fce4c7a/source/sab.ttl#L2527
![image](https://github.com/libris/definitions/assets/1894384/cd35389a-683f-4e02-b993-8a1e5b5304d4)
![image](https://github.com/libris/definitions/assets/1894384/81300d8f-97a3-4574-a01e-e7a0fd1c9679)

Exempel: _Aaxz_,, _Fv_, 

Det finns också ett antal (20st)  tomma comments: _Ibhc_, _Ijsac_

**Comment by niklasl** [comment]
Tack för rapporten! Förbättringar finns nu på develop-grenen.
